[package]
name = "RUSTSEC-2021-0028"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toodee = "0.2.0"