[package]
name = "RUSTSEC-2023-0005"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "=1.24.1", features = ["io-util", "rt", "macros"] }